basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is an api to manage students, teachers and academic processes
    in the university
  title: UNEG Services API
  version: "1.0"
paths: {}
swagger: "2.0"
